/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_udt_android_jni_AndroidUdt */

#ifndef _Included_com_udt_android_jni_AndroidUdt
#define _Included_com_udt_android_jni_AndroidUdt
#ifdef __cplusplus
extern "C" {
#endif
#undef com_udt_android_jni_AndroidUdt_AF_INET
#define com_udt_android_jni_AndroidUdt_AF_INET 2L
#undef com_udt_android_jni_AndroidUdt_ERROR
#define com_udt_android_jni_AndroidUdt_ERROR -1L
#undef com_udt_android_jni_AndroidUdt_SOCK_STREAM
#define com_udt_android_jni_AndroidUdt_SOCK_STREAM 1L
#undef com_udt_android_jni_AndroidUdt_SOCK_DGRAM
#define com_udt_android_jni_AndroidUdt_SOCK_DGRAM 2L
/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    recv
 * Signature: (I[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_udt_android_jni_AndroidUdt_recv
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    socket
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_com_udt_android_jni_AndroidUdt_socket
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_udt_android_jni_AndroidUdt_close
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    connect
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_udt_android_jni_AndroidUdt_connect
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    send
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_udt_android_jni_AndroidUdt_send
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    sendmsg
 * Signature: (I[BIIZ)I
 */
JNIEXPORT jint JNICALL Java_com_udt_android_jni_AndroidUdt_sendmsg
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jboolean);

/*
 * Class:     com_udt_android_jni_AndroidUdt
 * Method:    recvmsg
 * Signature: (I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_udt_android_jni_AndroidUdt_recvmsg
  (JNIEnv *, jobject, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
