/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vp8_decoder_YV12ToRGB32 */

#ifndef _Included_com_vp8_decoder_YV12ToRGB32
#define _Included_com_vp8_decoder_YV12ToRGB32
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vp8_decoder_YV12ToRGB32
 * Method:    convertC
 * Signature: ([B[B[BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_vp8_decoder_YV12ToRGB32_convertC
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
