/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yungamegl_GLRenderC */

#ifndef _Included_com_example_yungamegl_GLRenderC
#define _Included_com_example_yungamegl_GLRenderC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yungamegl_GLRenderC
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_yungamegl_GLRenderC_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_example_yungamegl_GLRenderC
 * Method:    nativeResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_yungamegl_GLRenderC_nativeResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_yungamegl_GLRenderC
 * Method:    nativeRenderer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_yungamegl_GLRenderC_nativeRenderer
  (JNIEnv *, jclass);

/*
 * Class:     com_example_yungamegl_GLRenderC
 * Method:    nativeSetSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_yungamegl_GLRenderC_nativeSetSize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_yungamegl_GLRenderC
 * Method:    nativeSetData
 * Signature: ([B[B[B)V
 */
JNIEXPORT void JNICALL Java_com_example_yungamegl_GLRenderC_nativeSetData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
