/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vp8_decoder_VPXDecoder */

#ifndef _Included_com_vp8_decoder_VPXDecoder
#define _Included_com_vp8_decoder_VPXDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vp8_decoder_VPXDecoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vp8_decoder_VPXDecoder_init
  (JNIEnv *, jobject);

/*
 * Class:     com_vp8_decoder_VPXDecoder
 * Method:    decode
 * Signature: ([BIIII)Lcom/vp8/decoder/YUVData;
 */
JNIEXPORT jobject JNICALL Java_com_vp8_decoder_VPXDecoder_decode
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_vp8_decoder_VPXDecoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vp8_decoder_VPXDecoder_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
